# Generated by Django 3.0.4 on 2020-03-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.FileField(upload_to='files')),
                ('sha_256', models.CharField(max_length=256)),
            ],
        ),
    ]
