# Generated by Django 3.0.4 on 2020-03-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=2048)),
                ('private_key', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='archive',
            field=models.FileField(upload_to='webservice/archives'),
        ),
    ]
