# Generated by Django 3.0.4 on 2020-03-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0002_auto_20200312_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200000)),
                ('serial_number', models.CharField(max_length=200000)),
                ('subject_public_key', models.FileField(upload_to='webservice/keys')),
                ('issuer', models.CharField(max_length=200000)),
                ('certificate', models.FileField(upload_to='webservice/certificate')),
            ],
        ),
        migrations.DeleteModel(
            name='KeyPair',
        ),
    ]
