# Generated by Django 3.0.4 on 2020-03-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certs', '0003_auto_20200314_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.FileField(upload_to='certificate'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='subject_public_key',
            field=models.FileField(upload_to='keys'),
        ),
        migrations.AlterField(
            model_name='file',
            name='archive',
            field=models.FileField(upload_to='archives'),
        ),
    ]
